### ISSUE TITLE
I had a lot of work this week

### ISSUE THREAD

**Issue by DriesOlbrechts** [Vonaclast/JavaLearning#6]
Hey, I said in telegram I would have 001 done by Saturday, but I had a really hard week in terms of school so I don't know if I will make it, I was able to do 01 and 02 but 02 hasn't been uploaded yet, I hope that you understand if I don't make it in time, but I will understand if this has consequences.

P.S: is this the right place to put this?

Thank you for understanding.

**Comment by Dries1234** [comment]
I have a feeling I didn't format correctly

**Comment by Vonaclast** [comment]
Hey Dries! 

Don't worry, it's not a problem - the only "consequence" is that on the 21st we will move on to 002, so you will (probably) see us talking less about 001 in general. However, as stated in the Progression document itself, you will still be able to ask us whatever you need, as long as you actively make an effort to reach the level of the rest of the group (in terms of exercise progression, that is).

To your P.S.: sure, Issues can be technical, theoretical and personal. :)

**Comment by DriesOlbrechts** [comment]
thank you, i will definately be able to get back to where you are because after next week I have a week off
