### ISSUE TITLE
JavaFX

### ISSUE THREAD

**Issue by mariodujic** [Vonaclast/JavaLearning#9]

**Comment by zunjae** [comment]
>-I'd need to, read size of file/folder

Just a tip, but google `read size of file and folder java` on Google. I found this StackOverflow link: https://stackoverflow.com/questions/2149785/get-size-of-folder-or-file and this comment: https://stackoverflow.com/a/25439778

The code is very simple:

```
public static long getSize(File file) {
    long size;
    if (file.isDirectory()) {
        size = 0;
        for (File child : file.listFiles()) {
            size += getSize(child);
        }
    } else {
        size = file.length();
    }
    return size;
}
```

getSize() requires a parameter of type File. To create a File object, use `File file = new File("/location/to/your/folder")`

---

>-compare it to previous size of file/folder

In order to do this, you need to save the size of the folder... You could just store the size in a variable. nothing difficult here.

```
long size = 0;
```

now next time store the results from getSize() into that variable.

**Comment by GroundZeroCro** [comment]
I'll just go with this Frankestain for now. This is my biggest project so far and I just wanna have src file saved, until I learn github.

`package application;
	
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;


public class Main extends Application {
	@Override
	public void start(Stage primaryStage) {
		try {
			Parent root = FXMLLoader.load(getClass().getResource("window.fxml"));
			Scene scene = new Scene(root);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage.setScene(scene);
			
			
			
			primaryStage.show();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void main(String[] args) {
		launch(args);
	}
}`

`package application;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.time.LocalDateTime;
import java.util.ResourceBundle;
import org.apache.commons.io.FileUtils;
import com.jfoenix.controls.JFXProgressBar;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.ProgressBar;
import javafx.scene.control.ProgressIndicator;


public class Controller implements Initializable{
	
	@FXML
	private JFXProgressBar bar;
	
	
	

	public void kopiranjeLokacije(ActionEvent event) {
			
		File srcDir = new File("C:\\Users\\Zero\\AndroidStudioProjects\\Molitvenik3\\app\\src");
		
		File destDir = new File("E:\\MolitvenikAndroidBackup\\"+LocalDateTime.now().toString().replace(":", " ").replace("-", " ").replace(".", " "));

		try {
			FileUtils.copyDirectory(srcDir, destDir);
			final ProgressBar pb = new ProgressBar(0);
			final ProgressIndicator pi =new ProgressIndicator(0);
			pi.startFullDrag();
			
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}	
	}



	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
	
	
			}

}`
